Executing workflow `uninstall` on deployment `gcp` [timeout=900 seconds]
2019-08-11 01:56:44.424  CFY <gcp> Starting 'uninstall' workflow execution
2019-08-11 01:56:45.839  CFY <gcp> [config-wordpress_vu0898->vm-app2_mboyi2|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 01:56:46.852  CFY <gcp> [config-database_27qtls->vm-database_77vjn4|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 01:56:47.731  CFY <gcp> [config-wordpress_vu0898] Validating node instance after deletion: nothing to do
2019-08-11 01:56:47.853  CFY <gcp> [firewall_lwjld4] Stopping node instance
2019-08-11 01:56:48.390  CFY <gcp> [config-database_27qtls] Validating node instance after deletion: nothing to do
2019-08-11 01:56:48.527  CFY <gcp> [config-wordpress_vu0898] Stop: instance already uninitialized
2019-08-11 01:56:48.627  CFY <gcp> [firewall_lwjld4] Validating node instance after deletion: nothing to do
2019-08-11 01:56:48.781  CFY <gcp> [config-database_27qtls] Stop: instance already uninitialized
2019-08-11 01:56:49.407  CFY <gcp> [firewall_lwjld4] Stopped node instance: nothing to do
2019-08-11 01:56:50.237  CFY <gcp> [config-wordpress_vu0898->vm-app2_mboyi2|unlink] Task failed 'cloudify_ansible.tasks.ansible_remove_host' -> 409: Node instance update conflict [current version=2, update version=1]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 524, in _run_operation_func
    ctx.source.instance.update()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/context.py", line 414, in update
    self._endpoint.update_node_instance(self._node_instance)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/endpoint.py", line 177, in update_node_instance
    return manager.update_node_instance(node_instance)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/manager.py", line 389, in update_node_instance
    version=node_instance.version)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/node_instances.py", line 141, in update
    response = self.api.patch(uri, data=data)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 311, in patch
    timeout=timeout)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/cluster.py", line 57, in do_request
    **kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 257, in do_request
    verify=self.get_request_verify(), timeout=timeout)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 191, in _do_request
    self._raise_client_error(response, request_url)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 144, in _raise_client_error
    response=response)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 156, in _prepare_and_raise_exception
    status_code, error_code=error_code, response=response)
CloudifyClientError: 409: Node instance update conflict [current version=2, update version=1]

2019-08-11 01:56:50.339  CFY <gcp> [config-wordpress_vu0898] Delete: instance already uninitialized
2019-08-11 01:56:50.631  CFY <gcp> [config-wordpress_vu0898->vm-app1_e0g2kn|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 01:56:51.805  CFY <gcp> [config-wordpress_vu0898] Deleted node instance
2019-08-11 01:56:51.942  CFY <gcp> [config-database_27qtls->vm-database_77vjn4|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 01:56:52.054  CFY <gcp> [config-database_27qtls] Delete: instance already uninitialized
2019-08-11 01:56:52.287  CFY <gcp> [firewall_lwjld4] Unlinking relationships
2019-08-11 01:56:53.159  CFY <gcp> [config-database_27qtls] Deleted node instance
2019-08-11 01:56:53.672  CFY <gcp> [firewall_lwjld4] Relationships unlinked
2019-08-11 01:56:54.017  CFY <gcp> [firewall_lwjld4] Deleting node instance
2019-08-11 01:56:54.788  CFY <gcp> [firewall_lwjld4.delete] Sending task 'cloudify_gcp.compute.firewall.delete'
2019-08-11 01:56:55.660  CFY <gcp> [config-wordpress_vu0898->vm-app1_e0g2kn|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 01:56:56.582  CFY <gcp> [vm-app1_e0g2kn] Validating node instance after deletion: nothing to do
2019-08-11 01:56:56.712  CFY <gcp> [vm-app2_mboyi2] Validating node instance after deletion: nothing to do
2019-08-11 01:56:56.825  CFY <gcp> [vm-app2_mboyi2] Stop: instance already uninitialized
2019-08-11 01:56:56.921  CFY <gcp> [vm-app1_e0g2kn] Stop: instance already uninitialized
2019-08-11 01:56:57.517  CFY <gcp> [vm-app2_mboyi2] Delete: instance already uninitialized
2019-08-11 01:56:57.586  CFY <gcp> [vm-app1_e0g2kn] Delete: instance already uninitialized
2019-08-11 01:56:57.706  CFY <gcp> [vm-app2_mboyi2] Deleted node instance
2019-08-11 01:56:58.545  LOG <gcp> [firewall_lwjld4.delete] INFO: Delete firewall rule firewall-lwjld4 from network https://www.googleapis.com/compute/v1/projects/node2faas-248113/global/networks/network-v57urb
2019-08-11 01:56:58.829  CFY <gcp> [vm-app1_e0g2kn] Deleted node instance
2019-08-11 01:56:59.461  CFY <gcp> [vm-database_77vjn4] Stopping node instance
2019-08-11 01:56:59.674  CFY <gcp> [vm-database_77vjn4] Validating node instance after deletion: nothing to do
2019-08-11 01:57:00.060  CFY <gcp> [vm-database_77vjn4] Stopped node instance: nothing to do
2019-08-11 01:57:00.580  CFY <gcp> [vm-database_77vjn4] Unlinking relationships
2019-08-11 01:57:00.820  CFY <gcp> [vm-database_77vjn4] Relationships unlinked
2019-08-11 01:57:01.053  CFY <gcp> [vm-database_77vjn4] Deleting node instance
2019-08-11 01:57:01.512  CFY <gcp> [firewall_lwjld4.delete] Task succeeded 'cloudify_gcp.compute.firewall.delete'
2019-08-11 01:57:01.550  CFY <gcp> [vm-database_77vjn4.delete] Sending task 'cloudify_gcp.compute.instance.delete'
2019-08-11 01:57:02.737  CFY <gcp> [firewall_lwjld4] Deleted node instance
2019-08-11 01:57:03.881  LOG <gcp> [vm-database_77vjn4.delete] INFO: Delete instance wordpressdatabase
2019-08-11 01:57:05.873  LOG <gcp> [vm-database_77vjn4.delete] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 457, in delete
    utils.delete_if_not_external(instance)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 175, in delete_if_not_external
    return resource.delete()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 133, in delete
    instance=self.name).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/us-east4-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/us-east4-c/instances/wordpressdatabase' was not found">
 with message <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/us-east4-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/us-east4-c/instances/wordpressdatabase' was not found">
2019-08-11 01:57:05.873  LOG <gcp> [vm-database_77vjn4.delete] ERROR: Error Message 
2019-08-11 01:57:06.558  CFY <gcp> [vm-database_77vjn4.delete] Task failed 'cloudify_gcp.compute.instance.delete'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError

2019-08-11 01:57:06.739  CFY <gcp> [vm-database_77vjn4] Deleted node instance
2019-08-11 01:57:07.108  CFY <gcp> [subnet_a7ram7] Stopping node instance
2019-08-11 01:57:07.393  CFY <gcp> [subnet_a7ram7] Validating node instance after deletion: nothing to do
2019-08-11 01:57:07.492  CFY <gcp> [subnet_a7ram7] Stopped node instance: nothing to do
2019-08-11 01:57:07.796  CFY <gcp> [subnet_a7ram7] Unlinking relationships
2019-08-11 01:57:08.080  CFY <gcp> [subnet_a7ram7] Relationships unlinked
2019-08-11 01:57:08.331  CFY <gcp> [subnet_a7ram7] Deleting node instance
2019-08-11 01:57:08.437  CFY <gcp> [subnet_a7ram7.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete'
2019-08-11 01:57:10.562  LOG <gcp> [subnet_a7ram7.delete] INFO: Delete subnetwork subnet-a7ram7
2019-08-11 01:57:13.171  CFY <gcp> [subnet_a7ram7.delete] Task rescheduled 'cloudify_gcp.compute.subnetwork.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-11 01:57:28.266  CFY <gcp> [subnet_a7ram7.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete' [retry 1/60]
2019-08-11 01:57:31.973  CFY <gcp> [subnet_a7ram7.delete] Task rescheduled 'cloudify_gcp.compute.subnetwork.delete' -> Operation not completed yet: RUNNING [retry_after=30] [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation not completed yet: RUNNING [retry_after=30]

2019-08-11 01:58:02.031  CFY <gcp> [subnet_a7ram7.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete' [retry 2/60]
2019-08-11 01:58:06.304  CFY <gcp> [subnet_a7ram7.delete] Task succeeded 'cloudify_gcp.compute.subnetwork.delete' [retry 2/60]
2019-08-11 01:58:06.562  CFY <gcp> [subnet_a7ram7] Deleted node instance
2019-08-11 01:58:06.898  CFY <gcp> [network_v57urb] Stopping node instance
2019-08-11 01:58:07.235  CFY <gcp> [network_v57urb] Validating node instance after deletion: nothing to do
2019-08-11 01:58:07.352  CFY <gcp> [network_v57urb] Stopped node instance: nothing to do
2019-08-11 01:58:07.641  CFY <gcp> [network_v57urb] Unlinking relationships
2019-08-11 01:58:07.913  CFY <gcp> [network_v57urb] Relationships unlinked
2019-08-11 01:58:08.172  CFY <gcp> [network_v57urb] Deleting node instance
2019-08-11 01:58:08.352  CFY <gcp> [network_v57urb.delete] Sending task 'cloudify_gcp.compute.network.delete'
2019-08-11 01:58:10.554  LOG <gcp> [network_v57urb.delete] INFO: Delete network network-v57urb
2019-08-11 01:58:13.272  CFY <gcp> [network_v57urb.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-11 01:58:28.379  CFY <gcp> [network_v57urb.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 1/60]
2019-08-11 01:58:32.321  CFY <gcp> [network_v57urb.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation not completed yet: RUNNING [retry_after=30] [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation not completed yet: RUNNING [retry_after=30]

2019-08-11 01:59:02.453  CFY <gcp> [network_v57urb.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-11 01:59:06.716  CFY <gcp> [network_v57urb.delete] Task succeeded 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-11 01:59:07.004  CFY <gcp> [network_v57urb] Deleted node instance
2019-08-11 01:59:07.401  CFY <gcp> 'uninstall' workflow execution succeeded
Finished executing workflow uninstall on deployment gcp
* Run 'cfy events list 6c24d59a-864a-4b66-8070-39c44cb8bffa' to retrieve the execution's events/logs
Trying to delete deployment gcp...
Deployment deleted
Deleting blueprint cloudify-1565488337-wp-gcp...
Blueprint deleted
