Executing workflow `uninstall` on deployment `gcp` [timeout=900 seconds]
2019-08-10 17:01:47.589  CFY <gcp> Starting 'uninstall' workflow execution
2019-08-10 17:01:48.432  CFY <gcp> [config-database_cccjuw] Validating node instance after deletion: nothing to do
2019-08-10 17:01:48.653  CFY <gcp> [config-database_cccjuw->vm-database_a3i2h9|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 17:01:50.004  CFY <gcp> [config-wordpress_u471ub->vm-app2_wa6st7|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 17:01:50.061  CFY <gcp> [firewall_o0eqse] Stopping node instance
2019-08-10 17:01:50.268  CFY <gcp> [config-wordpress_u471ub] Validating node instance after deletion: nothing to do
2019-08-10 17:01:51.385  CFY <gcp> [config-wordpress_u471ub] Stop: instance already uninitialized
2019-08-10 17:01:51.516  CFY <gcp> [config-database_cccjuw] Stop: instance already uninitialized
2019-08-10 17:01:51.648  CFY <gcp> [firewall_o0eqse] Validating node instance after deletion: nothing to do
2019-08-10 17:01:53.005  CFY <gcp> [firewall_o0eqse] Stopped node instance: nothing to do
2019-08-10 17:01:53.154  CFY <gcp> [config-wordpress_u471ub] Delete: instance already uninitialized
2019-08-10 17:01:53.371  CFY <gcp> [config-database_cccjuw] Delete: instance already uninitialized
2019-08-10 17:01:54.052  CFY <gcp> [config-database_cccjuw->vm-database_a3i2h9|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 17:01:54.434  CFY <gcp> [config-wordpress_u471ub] Deleted node instance
2019-08-10 17:01:55.163  CFY <gcp> [config-database_cccjuw] Deleted node instance
2019-08-10 17:01:55.679  CFY <gcp> [firewall_o0eqse] Unlinking relationships
2019-08-10 17:01:56.137  CFY <gcp> [config-wordpress_u471ub->vm-app2_wa6st7|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 17:01:56.143  CFY <gcp> [firewall_o0eqse] Relationships unlinked
2019-08-10 17:01:56.273  CFY <gcp> [config-wordpress_u471ub->vm-app1_ovgppw|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 17:01:57.523  CFY <gcp> [firewall_o0eqse] Deleting node instance
2019-08-10 17:01:57.870  CFY <gcp> [firewall_o0eqse.delete] Sending task 'cloudify_gcp.compute.firewall.delete'
2019-08-10 17:01:59.754  CFY <gcp> [config-wordpress_u471ub->vm-app1_ovgppw|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 17:02:00.467  CFY <gcp> [vm-app2_wa6st7] Validating node instance after deletion: nothing to do
2019-08-10 17:02:01.129  CFY <gcp> [vm-app1_ovgppw] Validating node instance after deletion: nothing to do
2019-08-10 17:02:01.257  CFY <gcp> [vm-app2_wa6st7] Stop: instance already uninitialized
2019-08-10 17:02:01.386  CFY <gcp> [vm-app1_ovgppw] Stop: instance already uninitialized
2019-08-10 17:02:02.090  LOG <gcp> [firewall_o0eqse.delete] INFO: Delete firewall rule firewall-o0eqse from network https://www.googleapis.com/compute/v1/projects/node2faas-248113/global/networks/network-db7mkq
2019-08-10 17:02:02.668  CFY <gcp> [vm-app2_wa6st7] Delete: instance already uninitialized
2019-08-10 17:02:02.823  CFY <gcp> [vm-app1_ovgppw] Delete: instance already uninitialized
2019-08-10 17:02:03.132  CFY <gcp> [vm-app2_wa6st7] Deleted node instance
2019-08-10 17:02:03.799  CFY <gcp> [vm-app1_ovgppw] Deleted node instance
2019-08-10 17:02:04.670  CFY <gcp> [vm-database_a3i2h9] Stopping node instance
2019-08-10 17:02:04.768  CFY <gcp> [vm-database_a3i2h9] Validating node instance after deletion: nothing to do
2019-08-10 17:02:05.099  CFY <gcp> [vm-database_a3i2h9] Stopped node instance: nothing to do
2019-08-10 17:02:05.713  CFY <gcp> [vm-database_a3i2h9] Unlinking relationships
2019-08-10 17:02:06.065  CFY <gcp> [firewall_o0eqse.delete] Task succeeded 'cloudify_gcp.compute.firewall.delete'
2019-08-10 17:02:06.345  CFY <gcp> [firewall_o0eqse] Deleted node instance
2019-08-10 17:02:06.410  CFY <gcp> [vm-database_a3i2h9] Relationships unlinked
2019-08-10 17:02:06.546  CFY <gcp> [vm-database_a3i2h9] Deleting node instance
2019-08-10 17:02:06.894  CFY <gcp> [vm-database_a3i2h9.delete] Sending task 'cloudify_gcp.compute.instance.delete'
2019-08-10 17:02:09.838  LOG <gcp> [vm-database_a3i2h9.delete] INFO: Delete instance wordpressdatabase
2019-08-10 17:02:11.386  LOG <gcp> [vm-database_a3i2h9.delete] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 457, in delete
    utils.delete_if_not_external(instance)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 175, in delete_if_not_external
    return resource.delete()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 133, in delete
    instance=self.name).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase' was not found">
 with message <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase' was not found">
2019-08-10 17:02:11.386  LOG <gcp> [vm-database_a3i2h9.delete] ERROR: Error Message 
2019-08-10 17:02:12.300  CFY <gcp> [vm-database_a3i2h9.delete] Task failed 'cloudify_gcp.compute.instance.delete'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError

2019-08-10 17:02:12.302  CFY <gcp> [vm-database_a3i2h9] Deleted node instance
2019-08-10 17:02:13.455  CFY <gcp> [subnet_8ufeli] Stopping node instance
2019-08-10 17:02:13.770  CFY <gcp> [subnet_8ufeli] Validating node instance after deletion: nothing to do
2019-08-10 17:02:14.122  CFY <gcp> [subnet_8ufeli] Stopped node instance: nothing to do
2019-08-10 17:02:14.631  CFY <gcp> [subnet_8ufeli] Unlinking relationships
2019-08-10 17:02:15.049  CFY <gcp> [subnet_8ufeli] Relationships unlinked
2019-08-10 17:02:15.345  CFY <gcp> [subnet_8ufeli] Deleting node instance
2019-08-10 17:02:15.605  CFY <gcp> [subnet_8ufeli.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete'
2019-08-10 17:02:17.752  LOG <gcp> [subnet_8ufeli.delete] INFO: Delete subnetwork subnet-8ufeli
2019-08-10 17:02:21.376  CFY <gcp> [subnet_8ufeli.delete] Task rescheduled 'cloudify_gcp.compute.subnetwork.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-10 17:02:36.446  CFY <gcp> [subnet_8ufeli.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete' [retry 1/60]
2019-08-10 17:02:40.758  CFY <gcp> [subnet_8ufeli.delete] Task succeeded 'cloudify_gcp.compute.subnetwork.delete' [retry 1/60]
2019-08-10 17:02:40.818  CFY <gcp> [subnet_8ufeli] Deleted node instance
2019-08-10 17:02:41.618  CFY <gcp> [network_db7mkq] Stopping node instance
2019-08-10 17:02:41.812  CFY <gcp> [network_db7mkq] Validating node instance after deletion: nothing to do
2019-08-10 17:02:41.888  CFY <gcp> [network_db7mkq] Stopped node instance: nothing to do
2019-08-10 17:02:42.310  CFY <gcp> [network_db7mkq] Unlinking relationships
2019-08-10 17:02:42.594  CFY <gcp> [network_db7mkq] Relationships unlinked
2019-08-10 17:02:42.779  CFY <gcp> [network_db7mkq] Deleting node instance
2019-08-10 17:02:43.156  CFY <gcp> [network_db7mkq.delete] Sending task 'cloudify_gcp.compute.network.delete'
2019-08-10 17:02:45.499  LOG <gcp> [network_db7mkq.delete] INFO: Delete network network-db7mkq
2019-08-10 17:02:47.871  CFY <gcp> [network_db7mkq.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-10 17:03:02.995  CFY <gcp> [network_db7mkq.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 1/60]
2019-08-10 17:03:08.024  CFY <gcp> [network_db7mkq.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation not completed yet: RUNNING [retry_after=30] [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation not completed yet: RUNNING [retry_after=30]

2019-08-10 17:03:38.119  CFY <gcp> [network_db7mkq.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-10 17:03:42.597  CFY <gcp> [network_db7mkq.delete] Task succeeded 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-10 17:03:42.709  CFY <gcp> [network_db7mkq] Deleted node instance
2019-08-10 17:03:43.529  CFY <gcp> 'uninstall' workflow execution succeeded
Finished executing workflow uninstall on deployment gcp
* Run 'cfy events list 804d7e98-03cd-419f-a21d-8102d13d6276' to retrieve the execution's events/logs
Trying to delete deployment gcp...
Deployment deleted
Deleting blueprint cloudify-wordpress-blueprint-gcp...
Blueprint deleted
