Uploading blueprint cloudify/azure.yaml...
 azure.yaml |##########################################################| 100.0%
Blueprint uploaded. The blueprint's id is cloudify-wordpress-blueprint-azure
Creating new deployment from blueprint cloudify-wordpress-blueprint-azure...
Deployment created. The deployment's id is azure
Executing workflow `install` on deployment `azure` [timeout=900 seconds]
Deployment environment creation is pending...
2019-08-08 07:19:31.363  CFY <azure> Starting 'create_deployment_environment' workflow execution
2019-08-08 07:19:31.366  CFY <azure> Installing deployment and workflow plugins
2019-08-08 07:19:31.466  CFY <azure> Sending task 'cloudify_agent.operations.install_plugins'
2019-08-08 07:19:31.482  CFY <azure> Task started 'cloudify_agent.operations.install_plugins'
2019-08-08 07:19:31.815  LOG <azure> INFO: Installing plugin: azure
2019-08-08 07:19:32.776  LOG <azure> INFO: Using existing installation of managed plugin: 804280e1-7edd-4fa8-9bc0-0d1a17de9a92 [package_name: cloudify-azure-plugin, package_version: 2.1.7, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:19:32.776  LOG <azure> INFO: Installing plugin: ansible
2019-08-08 07:19:33.535  LOG <azure> INFO: Using existing installation of managed plugin: 7142c593-6e52-429a-8a71-55266c022e02 [package_name: cloudify-ansible-plugin, package_version: 2.4.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:19:33.535  LOG <azure> INFO: Installing plugin: suspend
2019-08-08 07:19:34.830  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:19:34.830  LOG <azure> INFO: Installing plugin: scalelist
2019-08-08 07:19:35.578  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:19:35.578  LOG <azure> INFO: Installing plugin: configuration
2019-08-08 07:19:36.347  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 07:19:36.348  CFY <azure> Task succeeded 'cloudify_agent.operations.install_plugins'
2019-08-08 07:19:36.355  CFY <azure> Creating deployment work directory
2019-08-08 07:19:36.680  CFY <azure> 'create_deployment_environment' workflow execution succeeded
2019-08-08 07:19:39.825  CFY <azure> Starting 'install' workflow execution
2019-08-08 07:19:43.069  CFY <azure> [resource_group_jbl92z] Validating node instance before creation: nothing to do
2019-08-08 07:19:43.131  CFY <azure> [resource_group_jbl92z] Precreating node instance: nothing to do
2019-08-08 07:19:43.246  CFY <azure> [resource_group_jbl92z] Creating node instance
2019-08-08 07:19:43.485  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create'
2019-08-08 07:19:46.225  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:19:46.226  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:19:48.416  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:19:49.199  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:20:04.294  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 1/60]
2019-08-08 07:20:06.975  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:20:06.977  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:20:07.591  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:20:08.287  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:20:23.372  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 2/60]
2019-08-08 07:20:26.135  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:20:26.136  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:20:26.653  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:20:27.318  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 2/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:20:42.470  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 3/60]
2019-08-08 07:20:45.106  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:20:45.107  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:20:45.570  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:20:46.027  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 3/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:21:01.092  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 4/60]
2019-08-08 07:21:03.570  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:21:03.572  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:21:03.852  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:21:04.411  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 4/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:21:19.536  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 5/60]
2019-08-08 07:21:22.292  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:21:22.293  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:21:22.748  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:21:23.692  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 5/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:21:38.826  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 6/60]
2019-08-08 07:21:44.282  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:21:44.283  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:21:44.570  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:21:45.222  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 6/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:22:00.407  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 7/60]
2019-08-08 07:22:03.059  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:22:03.061  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:22:03.334  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:22:03.919  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 7/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:22:19.012  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 8/60]
2019-08-08 07:22:21.804  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:22:21.805  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:22:22.357  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:22:23.075  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 8/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:22:38.210  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 9/60]
2019-08-08 07:22:40.811  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:22:40.812  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:22:41.308  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:22:42.018  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 9/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:22:57.227  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 10/60]
2019-08-08 07:22:59.882  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:22:59.883  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:23:00.151  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:23:00.707  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 10/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:23:15.802  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 11/60]
2019-08-08 07:23:18.695  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:23:18.697  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:23:19.135  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:23:19.549  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 11/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:23:34.689  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 12/60]
2019-08-08 07:23:37.396  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:23:37.398  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:23:37.684  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:23:38.230  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 12/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:23:53.323  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 13/60]
2019-08-08 07:23:55.903  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:23:55.905  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:23:56.467  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:23:57.092  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 13/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:24:12.187  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 14/60]
2019-08-08 07:24:14.696  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:24:14.698  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:24:14.986  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:24:15.596  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 14/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:24:30.738  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 15/60]
2019-08-08 07:24:33.797  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:24:33.798  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:24:34.266  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:24:34.926  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 15/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:24:49.983  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 16/60]
2019-08-08 07:24:52.909  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:24:52.910  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:24:53.510  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:24:54.123  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 16/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:25:09.252  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 17/60]
2019-08-08 07:25:12.047  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:25:12.048  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:25:12.333  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:25:12.962  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 17/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:25:28.057  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 18/60]
2019-08-08 07:25:30.492  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:25:30.493  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:25:30.781  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:25:31.356  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 18/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:25:46.436  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 19/60]
2019-08-08 07:25:48.944  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:25:48.946  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:25:49.513  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:25:50.172  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 19/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:26:05.274  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 20/60]
2019-08-08 07:26:08.216  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:26:08.218  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:26:08.507  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:26:09.028  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 20/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:26:24.110  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 21/60]
2019-08-08 07:26:27.164  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:26:27.165  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:26:27.728  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:26:28.053  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 21/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:26:43.160  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 22/60]
2019-08-08 07:26:45.632  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:26:45.633  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:26:45.912  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:26:46.680  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 22/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:27:01.826  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 23/60]
2019-08-08 07:27:04.336  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:27:04.337  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:27:04.610  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:27:05.166  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 23/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:27:20.323  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 24/60]
2019-08-08 07:27:22.879  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:27:22.881  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:27:23.269  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:27:24.501  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 24/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:27:39.643  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 25/60]
2019-08-08 07:27:42.418  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:27:42.419  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:27:42.706  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:27:43.186  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 25/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:27:58.321  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 26/60]
2019-08-08 07:28:01.265  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:28:01.267  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:28:01.589  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:28:02.256  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 26/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:28:17.339  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 27/60]
2019-08-08 07:28:20.210  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:28:20.211  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:28:20.484  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:28:21.288  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 27/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:28:36.428  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 28/60]
2019-08-08 07:28:38.888  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:28:38.889  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:28:39.181  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:28:39.767  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 28/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:28:54.864  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 29/60]
2019-08-08 07:28:57.361  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:28:57.362  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:28:57.828  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:28:58.612  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 29/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:29:13.692  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 30/60]
2019-08-08 07:29:16.202  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:29:16.203  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:29:16.604  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:29:17.344  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 30/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:29:32.463  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 31/60]
2019-08-08 07:29:35.317  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:29:35.318  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:29:35.618  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:29:36.288  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 31/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:29:51.351  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 32/60]
2019-08-08 07:29:54.024  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:29:54.025  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:29:54.290  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:29:54.902  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 32/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:30:10.037  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 33/60]
2019-08-08 07:30:12.717  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:30:12.718  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:30:12.993  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:30:13.563  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 33/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:30:28.721  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 34/60]
2019-08-08 07:30:31.281  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:30:31.282  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:30:31.746  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:30:32.478  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 34/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:30:47.532  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 35/60]
2019-08-08 07:30:50.258  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:30:50.259  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:30:50.541  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:30:51.207  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 35/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:31:06.363  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 36/60]
2019-08-08 07:31:09.124  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:31:09.126  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:31:09.445  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:31:10.107  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 36/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:31:25.260  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 37/60]
2019-08-08 07:31:28.491  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:31:28.492  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:31:28.778  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:31:29.410  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 37/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:31:44.556  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 38/60]
2019-08-08 07:31:47.801  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:31:47.803  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:31:48.078  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:31:48.919  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 38/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:32:04.036  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 39/60]
2019-08-08 07:32:06.952  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:32:06.953  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:32:07.703  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:32:08.634  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 39/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:32:23.758  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 40/60]
2019-08-08 07:32:26.519  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:32:26.520  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:32:26.965  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:32:27.700  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 40/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:32:42.787  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 41/60]
2019-08-08 07:32:45.860  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:32:45.861  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:32:46.166  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:32:46.735  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 41/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:33:01.937  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 42/60]
2019-08-08 07:33:04.726  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:33:04.728  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:33:05.352  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:33:06.050  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 42/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:33:21.148  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 43/60]
2019-08-08 07:33:23.946  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:33:23.947  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:33:24.239  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:33:25.000  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 43/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:33:40.102  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 44/60]
2019-08-08 07:33:43.310  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:33:43.311  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:33:43.607  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:33:44.275  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 44/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:33:59.406  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 45/60]
2019-08-08 07:34:03.055  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:34:03.057  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:34:03.346  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:34:03.966  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 45/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 07:34:19.053  CFY <azure> [resource_group_jbl92z.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 46/60]
2019-08-08 07:34:21.808  LOG <azure> [resource_group_jbl92z.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 07:34:21.809  LOG <azure> [resource_group_jbl92z.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 07:34:22.110  LOG <azure> [resource_group_jbl92z.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 07:34:22.788  CFY <azure> [resource_group_jbl92z.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 46/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

Timed out waiting for workflow 'install' of deployment 'azure' to end. The execution may still be running properly; however, the command-line utility was instructed to wait up to 900 seconds for its completion.

* Run 'cfy executions list' to determine the execution's status.
* Run 'cfy executions cancel a91e337a-1ea7-429d-9f57-2e26dc79ee5a' to cancel the running workflow.
* Run 'cfy events list --tail a91e337a-1ea7-429d-9f57-2e26dc79ee5a' to retrieve the execution's events/logs
'Executing workflow `uninstall` on deployment `azure` [timeout=900 seconds] An error occurred on the server: 404: Requested `Deployment` with ID `azure` was not found Trying to delete deployment azure... An error occurred on the server: 404: Requested `Deployment` with ID `azure` was not found Deleting blueprint cloudify-wordpress-blueprint-azure... An error occurred on the server: 404: Requested `Blueprint` with ID `cloudify-wordpress-blueprint-azure` was not found'
