Executing workflow `uninstall` on deployment `gcp` [timeout=900 seconds]
2019-08-10 16:28:03.273  CFY <gcp> Starting 'uninstall' workflow execution
2019-08-10 16:28:04.124  CFY <gcp> [config-database_kz6djy] Validating node instance after deletion: nothing to do
2019-08-10 16:28:04.302  CFY <gcp> [config-wordpress_ggh2oz->vm-app2_ap91kt|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 16:28:05.530  CFY <gcp> [config-database_kz6djy->vm-database_rh9sm7|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 16:28:07.422  CFY <gcp> [config-wordpress_ggh2oz] Validating node instance after deletion: nothing to do
2019-08-10 16:28:07.592  CFY <gcp> [firewall_nhd0nu] Stopping node instance
2019-08-10 16:28:07.775  CFY <gcp> [config-database_kz6djy] Stop: instance already uninitialized
2019-08-10 16:28:07.928  CFY <gcp> [config-wordpress_ggh2oz] Stop: instance already uninitialized
2019-08-10 16:28:08.203  CFY <gcp> [firewall_nhd0nu] Validating node instance after deletion: nothing to do
2019-08-10 16:28:09.616  CFY <gcp> [config-wordpress_ggh2oz->vm-app2_ap91kt|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 16:28:09.928  CFY <gcp> [firewall_nhd0nu] Stopped node instance: nothing to do
2019-08-10 16:28:10.034  CFY <gcp> [config-wordpress_ggh2oz->vm-app1_4i5ar9|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 16:28:10.154  CFY <gcp> [config-database_kz6djy] Delete: instance already uninitialized
2019-08-10 16:28:11.057  CFY <gcp> [config-database_kz6djy] Deleted node instance
2019-08-10 16:28:11.099  CFY <gcp> [config-database_kz6djy->vm-database_rh9sm7|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 16:28:12.025  CFY <gcp> [config-wordpress_ggh2oz] Delete: instance already uninitialized
2019-08-10 16:28:12.232  CFY <gcp> [firewall_nhd0nu] Unlinking relationships
2019-08-10 16:28:12.408  CFY <gcp> [config-wordpress_ggh2oz] Deleted node instance
2019-08-10 16:28:13.169  CFY <gcp> [firewall_nhd0nu] Relationships unlinked
2019-08-10 16:28:13.382  CFY <gcp> [firewall_nhd0nu] Deleting node instance
2019-08-10 16:28:14.341  CFY <gcp> [firewall_nhd0nu.delete] Sending task 'cloudify_gcp.compute.firewall.delete'
2019-08-10 16:28:14.986  CFY <gcp> [config-wordpress_ggh2oz->vm-app1_4i5ar9|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 16:28:15.783  CFY <gcp> [vm-app1_4i5ar9] Validating node instance after deletion: nothing to do
2019-08-10 16:28:16.072  CFY <gcp> [vm-app2_ap91kt] Validating node instance after deletion: nothing to do
2019-08-10 16:28:16.628  CFY <gcp> [vm-app1_4i5ar9] Stop: instance already uninitialized
2019-08-10 16:28:16.737  CFY <gcp> [vm-app2_ap91kt] Stop: instance already uninitialized
2019-08-10 16:28:17.688  CFY <gcp> [vm-app1_4i5ar9] Delete: instance already uninitialized
2019-08-10 16:28:17.804  CFY <gcp> [vm-app2_ap91kt] Delete: instance already uninitialized
2019-08-10 16:28:17.948  CFY <gcp> [vm-app1_4i5ar9] Deleted node instance
2019-08-10 16:28:18.538  CFY <gcp> [vm-app2_ap91kt] Deleted node instance
2019-08-10 16:28:19.074  LOG <gcp> [firewall_nhd0nu.delete] INFO: Delete firewall rule firewall-nhd0nu from network https://www.googleapis.com/compute/v1/projects/node2faas-248113/global/networks/network-k0z4wp
2019-08-10 16:28:20.025  CFY <gcp> [vm-database_rh9sm7] Stopping node instance
2019-08-10 16:28:20.174  CFY <gcp> [vm-database_rh9sm7] Validating node instance after deletion: nothing to do
2019-08-10 16:28:20.588  CFY <gcp> [vm-database_rh9sm7] Stopped node instance: nothing to do
2019-08-10 16:28:21.423  CFY <gcp> [vm-database_rh9sm7] Unlinking relationships
2019-08-10 16:28:22.042  CFY <gcp> [vm-database_rh9sm7] Relationships unlinked
2019-08-10 16:28:22.275  CFY <gcp> [vm-database_rh9sm7] Deleting node instance
2019-08-10 16:28:22.656  CFY <gcp> [firewall_nhd0nu.delete] Task succeeded 'cloudify_gcp.compute.firewall.delete'
2019-08-10 16:28:23.215  CFY <gcp> [vm-database_rh9sm7.delete] Sending task 'cloudify_gcp.compute.instance.delete'
2019-08-10 16:28:23.487  CFY <gcp> [firewall_nhd0nu] Deleted node instance
2019-08-10 16:28:28.569  LOG <gcp> [vm-database_rh9sm7.delete] INFO: Delete instance wordpressdatabase
2019-08-10 16:28:31.158  LOG <gcp> [vm-database_rh9sm7.delete] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 457, in delete
    utils.delete_if_not_external(instance)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 175, in delete_if_not_external
    return resource.delete()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 133, in delete
    instance=self.name).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase' was not found">
 with message <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase' was not found">
2019-08-10 16:28:31.158  LOG <gcp> [vm-database_rh9sm7.delete] ERROR: Error Message 
2019-08-10 16:28:31.914  CFY <gcp> [vm-database_rh9sm7.delete] Task failed 'cloudify_gcp.compute.instance.delete'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError

2019-08-10 16:28:31.943  CFY <gcp> [vm-database_rh9sm7] Deleted node instance
2019-08-10 16:28:32.970  CFY <gcp> [subnet_422o3x] Stopping node instance
2019-08-10 16:28:33.152  CFY <gcp> [subnet_422o3x] Validating node instance after deletion: nothing to do
2019-08-10 16:28:33.234  CFY <gcp> [subnet_422o3x] Stopped node instance: nothing to do
2019-08-10 16:28:33.658  CFY <gcp> [subnet_422o3x] Unlinking relationships
2019-08-10 16:28:33.964  CFY <gcp> [subnet_422o3x] Relationships unlinked
2019-08-10 16:28:34.418  CFY <gcp> [subnet_422o3x] Deleting node instance
2019-08-10 16:28:34.616  CFY <gcp> [subnet_422o3x.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete'
2019-08-10 16:28:37.716  LOG <gcp> [subnet_422o3x.delete] INFO: Delete subnetwork subnet-422o3x
2019-08-10 16:28:40.151  CFY <gcp> [subnet_422o3x.delete] Task rescheduled 'cloudify_gcp.compute.subnetwork.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-10 16:28:55.218  CFY <gcp> [subnet_422o3x.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete' [retry 1/60]
2019-08-10 16:28:59.995  CFY <gcp> [subnet_422o3x.delete] Task rescheduled 'cloudify_gcp.compute.subnetwork.delete' -> Operation not completed yet: RUNNING [retry_after=30] [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation not completed yet: RUNNING [retry_after=30]

2019-08-10 16:29:30.122  CFY <gcp> [subnet_422o3x.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete' [retry 2/60]
2019-08-10 16:29:34.605  CFY <gcp> [subnet_422o3x.delete] Task succeeded 'cloudify_gcp.compute.subnetwork.delete' [retry 2/60]
2019-08-10 16:29:34.672  CFY <gcp> [subnet_422o3x] Deleted node instance
2019-08-10 16:29:35.727  CFY <gcp> [network_k0z4wp] Stopping node instance
2019-08-10 16:29:35.791  CFY <gcp> [network_k0z4wp] Validating node instance after deletion: nothing to do
2019-08-10 16:29:35.920  CFY <gcp> [network_k0z4wp] Stopped node instance: nothing to do
2019-08-10 16:29:36.539  CFY <gcp> [network_k0z4wp] Unlinking relationships
2019-08-10 16:29:36.985  CFY <gcp> [network_k0z4wp] Relationships unlinked
2019-08-10 16:29:37.302  CFY <gcp> [network_k0z4wp] Deleting node instance
2019-08-10 16:29:37.451  CFY <gcp> [network_k0z4wp.delete] Sending task 'cloudify_gcp.compute.network.delete'
2019-08-10 16:29:40.286  LOG <gcp> [network_k0z4wp.delete] INFO: Delete network network-k0z4wp
2019-08-10 16:29:42.992  CFY <gcp> [network_k0z4wp.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-10 16:29:58.111  CFY <gcp> [network_k0z4wp.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 1/60]
2019-08-10 16:30:02.645  CFY <gcp> [network_k0z4wp.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation not completed yet: RUNNING [retry_after=30] [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation not completed yet: RUNNING [retry_after=30]

2019-08-10 16:30:32.797  CFY <gcp> [network_k0z4wp.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-10 16:30:37.316  CFY <gcp> [network_k0z4wp.delete] Task succeeded 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-10 16:30:37.840  CFY <gcp> [network_k0z4wp] Deleted node instance
2019-08-10 16:30:38.403  CFY <gcp> 'uninstall' workflow execution succeeded
Finished executing workflow uninstall on deployment gcp
* Run 'cfy events list 91c9d583-49d3-4181-8bd3-f230ee6d8090' to retrieve the execution's events/logs
Trying to delete deployment gcp...
Deployment deleted
Deleting blueprint cloudify-wordpress-blueprint-gcp...
Blueprint deleted
