Uploading blueprint cloudify/azure.yaml...
 azure.yaml |##########################################################| 100.0%
Blueprint uploaded. The blueprint's id is cloudify-wordpress-blueprint-azure
Creating new deployment from blueprint cloudify-wordpress-blueprint-azure...
Deployment created. The deployment's id is azure
Executing workflow `install` on deployment `azure` [timeout=900 seconds]
Deployment environment creation is pending...
2019-08-08 14:11:16.078  CFY <azure> Starting 'create_deployment_environment' workflow execution
2019-08-08 14:11:16.082  CFY <azure> Installing deployment and workflow plugins
2019-08-08 14:11:16.186  CFY <azure> Sending task 'cloudify_agent.operations.install_plugins'
2019-08-08 14:11:16.198  CFY <azure> Task started 'cloudify_agent.operations.install_plugins'
2019-08-08 14:11:16.563  LOG <azure> INFO: Installing plugin: azure
2019-08-08 14:11:18.106  LOG <azure> INFO: Using existing installation of managed plugin: 804280e1-7edd-4fa8-9bc0-0d1a17de9a92 [package_name: cloudify-azure-plugin, package_version: 2.1.7, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 14:11:18.107  LOG <azure> INFO: Installing plugin: ansible
2019-08-08 14:11:19.272  LOG <azure> INFO: Using existing installation of managed plugin: 7142c593-6e52-429a-8a71-55266c022e02 [package_name: cloudify-ansible-plugin, package_version: 2.4.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 14:11:19.272  LOG <azure> INFO: Installing plugin: suspend
2019-08-08 14:11:20.276  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 14:11:20.276  LOG <azure> INFO: Installing plugin: scalelist
2019-08-08 14:11:21.708  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 14:11:21.708  LOG <azure> INFO: Installing plugin: configuration
2019-08-08 14:11:22.942  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 14:11:22.943  CFY <azure> Task succeeded 'cloudify_agent.operations.install_plugins'
2019-08-08 14:11:23.010  CFY <azure> Creating deployment work directory
2019-08-08 14:11:23.316  CFY <azure> 'create_deployment_environment' workflow execution succeeded
2019-08-08 14:11:28.049  CFY <azure> Starting 'install' workflow execution
2019-08-08 14:11:31.987  CFY <azure> [resource_group_yeedjm] Validating node instance before creation: nothing to do
2019-08-08 14:11:32.108  CFY <azure> [resource_group_yeedjm] Precreating node instance: nothing to do
2019-08-08 14:11:32.490  CFY <azure> [resource_group_yeedjm] Creating node instance
2019-08-08 14:11:32.669  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create'
2019-08-08 14:11:35.656  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:11:35.658  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:11:36.431  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:11:37.251  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:11:52.461  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 1/60]
2019-08-08 14:11:57.050  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:11:57.051  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:11:57.686  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:11:58.355  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:12:13.456  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 2/60]
2019-08-08 14:12:16.410  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:12:16.411  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:12:16.703  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:12:17.520  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 2/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:12:32.775  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 3/60]
2019-08-08 14:12:35.863  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:12:35.865  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:12:36.708  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:12:37.386  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 3/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:12:52.468  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 4/60]
2019-08-08 14:12:55.459  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:12:55.460  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:12:55.931  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:12:56.625  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 4/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:13:11.701  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 5/60]
2019-08-08 14:13:16.383  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:13:16.384  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:13:16.715  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:13:17.719  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 5/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:13:32.815  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 6/60]
2019-08-08 14:13:36.102  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:13:36.103  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:13:36.855  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:13:37.620  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 6/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:13:52.711  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 7/60]
2019-08-08 14:13:55.584  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:13:55.585  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:13:56.136  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:13:56.930  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 7/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:14:12.006  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 8/60]
2019-08-08 14:14:14.850  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:14:14.851  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:14:15.130  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:14:15.977  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 8/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:14:31.048  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 9/60]
2019-08-08 14:14:35.314  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:14:35.316  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:14:35.656  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:14:36.467  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 9/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:14:51.572  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 10/60]
2019-08-08 14:14:55.027  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:14:55.028  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:14:55.554  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:14:56.145  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 10/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:15:11.279  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 11/60]
2019-08-08 14:15:14.160  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:15:14.162  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:15:14.664  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:15:15.439  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 11/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:15:30.582  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 12/60]
2019-08-08 14:15:33.531  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:15:33.532  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:15:34.042  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:15:34.732  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 12/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:15:49.873  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 13/60]
2019-08-08 14:15:52.698  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:15:52.700  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:15:52.980  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:15:53.440  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 13/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:16:08.583  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 14/60]
2019-08-08 14:16:11.877  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:16:11.879  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:16:12.223  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:16:12.793  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 14/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:16:27.866  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 15/60]
2019-08-08 14:16:30.778  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:16:30.779  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:16:31.059  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:16:31.829  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 15/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:16:46.952  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 16/60]
2019-08-08 14:16:49.695  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:16:49.697  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:16:50.252  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:16:51.030  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 16/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:17:06.115  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 17/60]
2019-08-08 14:17:09.425  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:17:09.427  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:17:10.115  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:17:10.678  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 17/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:17:25.806  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 18/60]
2019-08-08 14:17:28.945  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:17:28.946  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:17:29.276  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:17:29.991  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 18/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:17:45.119  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 19/60]
2019-08-08 14:17:48.525  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:17:48.526  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:17:48.946  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:17:49.506  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 19/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:18:04.667  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 20/60]
2019-08-08 14:18:07.507  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:18:07.508  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:18:07.773  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:18:08.424  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 20/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:18:23.501  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 21/60]
2019-08-08 14:18:26.120  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:18:26.122  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:18:26.662  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:18:27.265  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 21/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:18:42.405  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 22/60]
2019-08-08 14:18:45.550  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:18:45.551  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:18:45.867  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:18:46.568  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 22/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:19:01.696  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 23/60]
2019-08-08 14:19:04.672  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:19:04.673  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:19:05.243  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:19:06.088  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 23/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:19:21.240  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 24/60]
2019-08-08 14:19:23.980  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:19:23.982  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:19:24.287  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:19:25.030  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 24/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:19:40.176  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 25/60]
2019-08-08 14:19:42.896  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:19:42.897  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:19:43.197  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:19:43.948  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 25/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:19:59.091  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 26/60]
2019-08-08 14:20:02.060  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:20:02.061  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:20:02.528  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:20:03.256  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 26/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:20:18.417  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 27/60]
2019-08-08 14:20:22.490  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:20:22.491  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:20:22.947  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:20:23.664  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 27/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:20:38.811  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 28/60]
2019-08-08 14:20:41.569  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:20:41.571  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:20:42.004  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:20:42.665  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 28/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:20:57.881  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 29/60]
2019-08-08 14:21:00.715  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:21:00.717  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:21:01.084  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:21:01.822  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 29/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:21:16.981  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 30/60]
2019-08-08 14:21:20.570  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:21:20.571  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:21:21.061  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:21:21.782  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 30/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:21:36.929  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 31/60]
2019-08-08 14:21:40.146  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:21:40.148  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:21:40.419  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:21:41.130  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 31/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:21:56.274  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 32/60]
2019-08-08 14:21:59.290  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:21:59.291  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:21:59.557  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:22:00.029  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 32/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:22:15.140  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 33/60]
2019-08-08 14:22:18.436  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:22:18.438  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:22:19.215  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:22:20.136  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 33/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:22:35.202  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 34/60]
2019-08-08 14:22:38.627  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:22:38.628  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:22:38.948  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:22:39.618  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 34/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:22:54.780  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 35/60]
2019-08-08 14:22:57.893  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:22:57.894  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:22:58.409  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:22:59.161  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 35/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:23:14.304  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 36/60]
2019-08-08 14:23:17.396  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:23:17.397  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:23:17.674  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:23:18.168  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 36/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:23:33.378  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 37/60]
2019-08-08 14:23:36.170  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:23:36.171  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:23:36.668  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:23:37.337  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 37/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:23:52.400  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 38/60]
2019-08-08 14:23:55.231  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:23:55.232  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:23:55.886  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:23:56.715  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 38/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:24:11.862  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 39/60]
2019-08-08 14:24:14.957  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:24:14.958  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:24:15.376  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:24:16.069  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 39/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:24:31.139  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 40/60]
2019-08-08 14:24:34.645  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:24:34.646  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:24:35.237  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:24:35.908  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 40/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:24:51.014  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 41/60]
2019-08-08 14:24:54.248  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:24:54.250  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:24:54.955  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:24:55.628  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 41/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:25:10.686  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 42/60]
2019-08-08 14:25:13.429  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:25:13.431  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:25:13.718  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:25:14.243  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 42/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:25:29.397  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 43/60]
2019-08-08 14:25:32.199  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:25:32.201  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:25:32.568  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:25:33.399  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 43/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:25:48.598  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 44/60]
2019-08-08 14:25:51.517  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:25:51.518  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:25:51.843  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:25:52.591  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 44/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 14:26:07.743  CFY <azure> [resource_group_yeedjm.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 45/60]
2019-08-08 14:26:10.377  LOG <azure> [resource_group_yeedjm.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 14:26:10.378  LOG <azure> [resource_group_yeedjm.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'UK-South', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 14:26:10.656  LOG <azure> [resource_group_yeedjm.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'UK-South' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 14:26:11.314  CFY <azure> [resource_group_yeedjm.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 45/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

Timed out waiting for workflow 'install' of deployment 'azure' to end. The execution may still be running properly; however, the command-line utility was instructed to wait up to 900 seconds for its completion.

* Run 'cfy executions list' to determine the execution's status.
* Run 'cfy executions cancel 3ad9c03a-0ed7-4293-b1bb-adbc30354a84' to cancel the running workflow.
* Run 'cfy events list --tail 3ad9c03a-0ed7-4293-b1bb-adbc30354a84' to retrieve the execution's events/logs
