Uploading blueprint cloudify/azure.yaml...
 azure.yaml |##########################################################| 100.0%
Blueprint uploaded. The blueprint's id is cloudify-wordpress-blueprint-azure
Creating new deployment from blueprint cloudify-wordpress-blueprint-azure...
Deployment created. The deployment's id is azure
Executing workflow `install` on deployment `azure` [timeout=900 seconds]
Deployment environment creation is pending...
2019-08-08 09:37:49.092  CFY <azure> Starting 'create_deployment_environment' workflow execution
2019-08-08 09:37:49.096  CFY <azure> Installing deployment and workflow plugins
2019-08-08 09:37:49.197  CFY <azure> Sending task 'cloudify_agent.operations.install_plugins'
2019-08-08 09:37:49.212  CFY <azure> Task started 'cloudify_agent.operations.install_plugins'
2019-08-08 09:37:49.552  LOG <azure> INFO: Installing plugin: azure
2019-08-08 09:37:50.441  LOG <azure> INFO: Using existing installation of managed plugin: 804280e1-7edd-4fa8-9bc0-0d1a17de9a92 [package_name: cloudify-azure-plugin, package_version: 2.1.7, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 09:37:50.441  LOG <azure> INFO: Installing plugin: ansible
2019-08-08 09:37:51.398  LOG <azure> INFO: Using existing installation of managed plugin: 7142c593-6e52-429a-8a71-55266c022e02 [package_name: cloudify-ansible-plugin, package_version: 2.4.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 09:37:51.399  LOG <azure> INFO: Installing plugin: suspend
2019-08-08 09:37:52.838  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 09:37:52.838  LOG <azure> INFO: Installing plugin: configuration
2019-08-08 09:37:53.717  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 09:37:53.718  LOG <azure> INFO: Installing plugin: scalelist
2019-08-08 09:37:54.624  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 09:37:54.625  CFY <azure> Task succeeded 'cloudify_agent.operations.install_plugins'
2019-08-08 09:37:54.627  CFY <azure> Creating deployment work directory
2019-08-08 09:37:55.052  CFY <azure> 'create_deployment_environment' workflow execution succeeded
2019-08-08 09:38:00.848  CFY <azure> Starting 'install' workflow execution
2019-08-08 09:38:04.837  CFY <azure> [resource_group_gmumh5] Validating node instance before creation: nothing to do
2019-08-08 09:38:04.932  CFY <azure> [resource_group_gmumh5] Precreating node instance: nothing to do
2019-08-08 09:38:05.219  CFY <azure> [resource_group_gmumh5] Creating node instance
2019-08-08 09:38:05.387  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create'
2019-08-08 09:38:08.430  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:38:08.433  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:38:09.573  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:38:10.382  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:38:25.506  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 1/60]
2019-08-08 09:38:29.530  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:38:29.532  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:38:30.081  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:38:30.976  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:38:46.174  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 2/60]
2019-08-08 09:38:48.960  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:38:48.961  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:38:49.433  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:38:49.958  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 2/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:39:05.095  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 3/60]
2019-08-08 09:39:07.826  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:39:07.827  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:39:08.304  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:39:09.156  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 3/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:39:24.293  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 4/60]
2019-08-08 09:39:27.053  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:39:27.054  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:39:27.531  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:39:28.051  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 4/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:39:43.203  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 5/60]
2019-08-08 09:39:46.241  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:39:46.242  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:39:46.674  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:39:47.400  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 5/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:40:02.588  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 6/60]
2019-08-08 09:40:05.272  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:40:05.273  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:40:05.790  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:40:06.300  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 6/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:40:21.418  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 7/60]
2019-08-08 09:40:24.080  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:40:24.082  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:40:24.525  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:40:25.183  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 7/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:40:40.409  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 8/60]
2019-08-08 09:40:42.814  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:40:42.815  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:40:43.179  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:40:43.936  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 8/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:40:59.067  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 9/60]
2019-08-08 09:41:01.646  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:41:01.647  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:41:02.086  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:41:02.928  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 9/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:41:18.038  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 10/60]
2019-08-08 09:41:21.173  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:41:21.175  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:41:21.627  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:41:22.432  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 10/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:41:37.608  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 11/60]
2019-08-08 09:41:40.409  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:41:40.411  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:41:40.673  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:41:41.336  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 11/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:41:56.568  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 12/60]
2019-08-08 09:41:59.352  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:41:59.353  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:41:59.833  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:42:00.511  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 12/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:42:15.637  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 13/60]
2019-08-08 09:42:18.398  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:42:18.400  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:42:18.887  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:42:19.667  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 13/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:42:34.778  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 14/60]
2019-08-08 09:42:37.695  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:42:37.697  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:42:38.168  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:42:38.770  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 14/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:42:53.886  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 15/60]
2019-08-08 09:42:56.667  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:42:56.668  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:42:56.956  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:42:57.707  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 15/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:43:12.847  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 16/60]
2019-08-08 09:43:15.541  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:43:15.543  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:43:15.851  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:43:16.612  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 16/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:43:31.770  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 17/60]
2019-08-08 09:43:34.811  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:43:34.812  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:43:35.110  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:43:35.735  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 17/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:43:50.884  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 18/60]
2019-08-08 09:43:53.563  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:43:53.565  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:43:54.233  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:43:54.934  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 18/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:44:10.088  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 19/60]
2019-08-08 09:44:12.651  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:44:12.652  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:44:12.948  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:44:13.407  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 19/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:44:28.596  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 20/60]
2019-08-08 09:44:31.305  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:44:31.306  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:44:31.682  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:44:32.346  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 20/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:44:47.469  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 21/60]
2019-08-08 09:44:50.370  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:44:50.372  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:44:50.657  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:44:51.219  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 21/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:45:06.370  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 22/60]
2019-08-08 09:45:09.409  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:45:09.411  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:45:10.009  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:45:10.725  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 22/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:45:25.852  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 23/60]
2019-08-08 09:45:28.663  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:45:28.665  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:45:28.933  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:45:29.640  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 23/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:45:44.792  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 24/60]
2019-08-08 09:45:47.389  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:45:47.390  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:45:47.911  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:45:48.647  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 24/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:46:03.870  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 25/60]
2019-08-08 09:46:06.324  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:46:06.325  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:46:06.651  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:46:07.165  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 25/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:46:22.318  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 26/60]
2019-08-08 09:46:25.225  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:46:25.226  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:46:25.634  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:46:26.486  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 26/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:46:41.559  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 27/60]
2019-08-08 09:46:44.490  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:46:44.491  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:46:44.786  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:46:45.511  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 27/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:47:00.609  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 28/60]
2019-08-08 09:47:03.367  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:47:03.368  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:47:03.944  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:47:04.569  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 28/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:47:19.713  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 29/60]
2019-08-08 09:47:22.272  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:47:22.273  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:47:22.552  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:47:23.140  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 29/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:47:38.281  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 30/60]
2019-08-08 09:47:41.058  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:47:41.059  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:47:41.336  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:47:42.142  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 30/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:47:57.305  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 31/60]
2019-08-08 09:48:00.133  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:48:00.134  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:48:00.469  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:48:01.269  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 31/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:48:16.397  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 32/60]
2019-08-08 09:48:19.293  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:48:19.294  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:48:19.855  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:48:20.569  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 32/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:48:35.726  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 33/60]
2019-08-08 09:48:38.630  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:48:38.632  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:48:39.033  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:48:39.678  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 33/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:48:54.867  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 34/60]
2019-08-08 09:48:57.662  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:48:57.664  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:48:57.949  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:48:58.575  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 34/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:49:13.725  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 35/60]
2019-08-08 09:49:21.391  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:49:21.392  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:49:21.667  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:49:22.306  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 35/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:49:37.427  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 36/60]
2019-08-08 09:49:40.032  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:49:40.033  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:49:40.305  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:49:40.760  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 36/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:49:55.824  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 37/60]
2019-08-08 09:49:58.489  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:49:58.490  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:49:58.778  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:49:59.365  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 37/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:50:14.520  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 38/60]
2019-08-08 09:50:17.068  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:50:17.070  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:50:17.334  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:50:17.860  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 38/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:50:32.928  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 39/60]
2019-08-08 09:50:36.007  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:50:36.008  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:50:36.305  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:50:36.881  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 39/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:50:52.011  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 40/60]
2019-08-08 09:50:54.754  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:50:54.755  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:50:55.838  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:50:56.582  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 40/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:51:11.700  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 41/60]
2019-08-08 09:51:14.274  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:51:14.276  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:51:14.539  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:51:15.129  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 41/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:51:30.238  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 42/60]
2019-08-08 09:51:33.014  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:51:33.016  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:51:33.289  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:51:33.822  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 42/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:51:48.940  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 43/60]
2019-08-08 09:51:51.690  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:51:51.691  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:51:52.045  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:51:52.577  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 43/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:52:07.719  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 44/60]
2019-08-08 09:52:10.461  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:52:10.462  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:52:10.769  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:52:11.252  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 44/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:52:26.345  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 45/60]
2019-08-08 09:52:29.751  LOG <azure> [resource_group_gmumh5.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 09:52:29.752  LOG <azure> [resource_group_gmumh5.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 09:52:30.220  LOG <azure> [resource_group_gmumh5.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 09:52:30.931  CFY <azure> [resource_group_gmumh5.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 45/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 09:52:46.074  CFY <azure> [resource_group_gmumh5.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 46/60]
Timed out waiting for workflow 'install' of deployment 'azure' to end. The execution may still be running properly; however, the command-line utility was instructed to wait up to 900 seconds for its completion.

* Run 'cfy executions list' to determine the execution's status.
* Run 'cfy executions cancel 1129387d-c201-4303-b9e3-f6ea60028750' to cancel the running workflow.
* Run 'cfy events list --tail 1129387d-c201-4303-b9e3-f6ea60028750' to retrieve the execution's events/logs
'Executing workflow `uninstall` on deployment `azure` [timeout=900 seconds] 2019-08-08 09:36:57.039 CFY <azure> Starting 'uninstall' workflow execution 2019-08-08 09:36:58.776 CFY <azure> [config-wordpress_2539jw] Validating node instance after deletion: nothing to do 2019-08-08 09:36:58.900 CFY <azure> [config-wordpress_2539jw->vm-app2_tuq4ki|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 09:36:59.739 CFY <azure> [config-database_ca8xw6] Validating node instance after deletion: nothing to do 2019-08-08 09:37:00.058 CFY <azure> [config-database_ca8xw6->vm-database_ausps5|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 09:37:01.220 CFY <azure> [config-database_ca8xw6] Stop: instance already deleted 2019-08-08 09:37:01.384 CFY <azure> [config-wordpress_2539jw] Stop: instance already deleted 2019-08-08 09:37:01.492 CFY <azure> [config-database_ca8xw6] Delete: instance already deleted 2019-08-08 09:37:01.698 CFY <azure> [config-wordpress_2539jw] Delete: instance already deleted 2019-08-08 09:37:02.437 CFY <azure> [config-wordpress_2539jw->vm-app2_tuq4ki|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 09:37:02.617 CFY <azure> [config-wordpress_2539jw->vm-app1_0tfzu6|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 09:37:03.635 CFY <azure> [config-database_ca8xw6->vm-database_ausps5|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 09:37:04.232 CFY <azure> [vm-database_ausps5] Validating node instance after deletion: nothing to do 2019-08-08 09:37:04.405 CFY <azure> [vm-database_ausps5] Stop: instance already deleted 2019-08-08 09:37:04.508 CFY <azure> [vm-database_ausps5] Delete: instance already deleted 2019-08-08 09:37:04.923 CFY <azure> [nic-db_fhxrtp] Validating node instance after deletion: nothing to do 2019-08-08 09:37:05.104 CFY <azure> [nic-db_fhxrtp] Stop: instance already deleted 2019-08-08 09:37:05.326 CFY <azure> [nic-db_fhxrtp] Delete: instance already deleted 2019-08-08 09:37:05.991 CFY <azure> [ip_config-db_k5b0z4] Validating node instance after deletion: nothing to do 2019-08-08 09:37:06.104 CFY <azure> [config-wordpress_2539jw->vm-app1_0tfzu6|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host' 2019-08-08 09:37:06.462 CFY <azure> [vm-app2_tuq4ki] Validating node instance after deletion: nothing to do 2019-08-08 09:37:06.609 CFY <azure> [ip_config-db_k5b0z4] Stop: instance already deleted 2019-08-08 09:37:06.767 CFY <azure> [vm-app1_0tfzu6] Validating node instance after deletion: nothing to do 2019-08-08 09:37:07.020 CFY <azure> [vm-app2_tuq4ki] Stop: instance already deleted 2019-08-08 09:37:07.077 CFY <azure> [vm-app1_0tfzu6] Stop: instance already deleted 2019-08-08 09:37:07.179 CFY <azure> [ip_config-db_k5b0z4] Delete: instance already deleted 2019-08-08 09:37:07.250 CFY <azure> [vm-app2_tuq4ki] Delete: instance already deleted 2019-08-08 09:37:07.305 CFY <azure> [vm-app1_0tfzu6] Delete: instance already deleted 2019-08-08 09:37:07.765 CFY <azure> [nic2_vban0m] Validating node instance after deletion: nothing to do 2019-08-08 09:37:08.423 CFY <azure> [availability_set_5xngty] Validating node instance after deletion: nothing to do 2019-08-08 09:37:08.551 CFY <azure> [ip-db_afb9cm] Validating node instance after deletion: nothing to do 2019-08-08 09:37:08.658 CFY <azure> [storage_account_65vas5] Validating node instance after deletion: nothing to do 2019-08-08 09:37:08.740 CFY <azure> [nic1_xaimkb] Validating node instance after deletion: nothing to do 2019-08-08 09:37:08.797 CFY <azure> [nic2_vban0m] Stop: instance already deleted 2019-08-08 09:37:08.853 CFY <azure> [availability_set_5xngty] Stop: instance already deleted 2019-08-08 09:37:08.911 CFY <azure> [nic1_xaimkb] Stop: instance already deleted 2019-08-08 09:37:08.976 CFY <azure> [storage_account_65vas5] Stop: instance already deleted 2019-08-08 09:37:09.028 CFY <azure> [ip-db_afb9cm] Stop: instance already deleted 2019-08-08 09:37:09.084 CFY <azure> [availability_set_5xngty] Delete: instance already deleted 2019-08-08 09:37:09.145 CFY <azure> [nic2_vban0m] Delete: instance already deleted 2019-08-08 09:37:09.205 CFY <azure> [nic1_xaimkb] Delete: instance already deleted 2019-08-08 09:37:09.318 CFY <azure> [ip-db_afb9cm] Delete: instance already deleted 2019-08-08 09:37:09.428 CFY <azure> [storage_account_65vas5] Delete: instance already deleted 2019-08-08 09:37:09.906 CFY <azure> [network_security_group_zjoh0g] Validating node instance after deletion: nothing to do 2019-08-08 09:37:10.073 CFY <azure> [ip_config1_nsym4r] Validating node instance after deletion: nothing to do 2019-08-08 09:37:10.477 CFY <azure> [ip_config2_xejiv2] Validating node instance after deletion: nothing to do 2019-08-08 09:37:10.661 CFY <azure> [network_security_group_zjoh0g] Stop: instance already deleted 2019-08-08 09:37:10.724 CFY <azure> [ip_config1_nsym4r] Stop: instance already deleted 2019-08-08 09:37:10.784 CFY <azure> [ip_config2_xejiv2] Stop: instance already deleted 2019-08-08 09:37:10.839 CFY <azure> [network_security_group_zjoh0g] Delete: instance already deleted 2019-08-08 09:37:10.898 CFY <azure> [ip_config1_nsym4r] Delete: instance already deleted 2019-08-08 09:37:11.058 CFY <azure> [ip_config2_xejiv2] Delete: instance already deleted 2019-08-08 09:37:11.237 CFY <azure> [subnet_2doat5] Validating node instance after deletion: nothing to do 2019-08-08 09:37:11.408 CFY <azure> [ip1_jjkp47] Validating node instance after deletion: nothing to do 2019-08-08 09:37:11.723 CFY <azure> [ip2_654yb4] Validating node instance after deletion: nothing to do 2019-08-08 09:37:11.920 CFY <azure> [ip2_654yb4] Stop: instance already deleted 2019-08-08 09:37:11.982 CFY <azure> [subnet_2doat5] Stop: instance already deleted 2019-08-08 09:37:12.036 CFY <azure> [ip1_jjkp47] Stop: instance already deleted 2019-08-08 09:37:12.091 CFY <azure> [subnet_2doat5] Delete: instance already deleted 2019-08-08 09:37:12.146 CFY <azure> [ip2_654yb4] Delete: instance already deleted 2019-08-08 09:37:12.526 CFY <azure> [network_oy3spz] Validating node instance after deletion: nothing to do 2019-08-08 09:37:12.598 CFY <azure> [ip1_jjkp47] Delete: instance already deleted 2019-08-08 09:37:12.806 CFY <azure> [network_oy3spz] Stop: instance already deleted 2019-08-08 09:37:12.986 CFY <azure> [network_oy3spz] Delete: instance already deleted 2019-08-08 09:37:13.132 CFY <azure> [resource_group_nw6hrj] Validating node instance after deletion: nothing to do 2019-08-08 09:37:13.447 CFY <azure> [resource_group_nw6hrj] Stop: instance already deleted Execution ended, waiting 3 seconds for additional log messages 2019-08-08 09:37:13.649 CFY <azure> [resource_group_nw6hrj] Delete: instance already deleted 2019-08-08 09:37:13.882 CFY <azure> 'uninstall' workflow execution succeeded Finished executing workflow uninstall on deployment azure cloudify common logs monitors play_test.sh README.md reset_test.sh results stop_test.sh temp_count temp_cpu_amount temp_io_amount temp_mem_amount temp_mem_initial temp_mem_total temp_monitor_pid temp_net_amount terraform Run 'cfy events list 7de7cb7c-6e17-43be-bdd0-58dfde147b10' to retrieve the execution's events/logs Trying to delete deployment azure... Deployment deleted Deleting blueprint cloudify-wordpress-blueprint-azure... Blueprint deleted Trying to delete deployment azure... An error occurred on the server: 404: Requested `Deployment` with ID `azure` was not found Deleting blueprint cloudify-wordpress-blueprint-azure... An error occurred on the server: 404: Requested `Blueprint` with ID `cloudify-wordpress-blueprint-azure` was not found'
