Uploading blueprint cloudify/azure.yaml...
 azure.yaml |##########################################################| 100.0%
Blueprint uploaded. The blueprint's id is cloudify-wordpress-blueprint-azure
Creating new deployment from blueprint cloudify-wordpress-blueprint-azure...
Deployment created. The deployment's id is azure
Executing workflow `install` on deployment `azure` [timeout=900 seconds]
Deployment environment creation is pending...
2019-08-08 12:55:31.286  CFY <azure> Starting 'create_deployment_environment' workflow execution
2019-08-08 12:55:31.290  CFY <azure> Installing deployment and workflow plugins
2019-08-08 12:55:31.391  CFY <azure> Sending task 'cloudify_agent.operations.install_plugins'
2019-08-08 12:55:31.406  CFY <azure> Task started 'cloudify_agent.operations.install_plugins'
2019-08-08 12:55:31.743  LOG <azure> INFO: Installing plugin: azure
2019-08-08 12:55:32.529  LOG <azure> INFO: Using existing installation of managed plugin: 804280e1-7edd-4fa8-9bc0-0d1a17de9a92 [package_name: cloudify-azure-plugin, package_version: 2.1.7, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 12:55:32.530  LOG <azure> INFO: Installing plugin: ansible
2019-08-08 12:55:33.498  LOG <azure> INFO: Using existing installation of managed plugin: 7142c593-6e52-429a-8a71-55266c022e02 [package_name: cloudify-ansible-plugin, package_version: 2.4.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 12:55:33.498  LOG <azure> INFO: Installing plugin: suspend
2019-08-08 12:55:34.935  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 12:55:34.935  LOG <azure> INFO: Installing plugin: scalelist
2019-08-08 12:55:35.739  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 12:55:35.739  LOG <azure> INFO: Installing plugin: configuration
2019-08-08 12:55:36.637  CFY <azure> Task succeeded 'cloudify_agent.operations.install_plugins'
2019-08-08 12:55:36.637  LOG <azure> INFO: Using existing installation of managed plugin: 62c3cd35-5a18-49fd-a670-48f9ad207b05 [package_name: cloudify-utilities-plugin, package_version: 1.14.0, supported_platform: linux_x86_64, distribution: centos, distribution_release: core]
2019-08-08 12:55:36.731  CFY <azure> Creating deployment work directory
2019-08-08 12:55:37.118  CFY <azure> 'create_deployment_environment' workflow execution succeeded
2019-08-08 12:55:42.990  CFY <azure> Starting 'install' workflow execution
2019-08-08 12:55:46.433  CFY <azure> [resource_group_pflaaj] Validating node instance before creation: nothing to do
2019-08-08 12:55:46.558  CFY <azure> [resource_group_pflaaj] Precreating node instance: nothing to do
2019-08-08 12:55:46.646  CFY <azure> [resource_group_pflaaj] Creating node instance
2019-08-08 12:55:47.005  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create'
2019-08-08 12:55:49.862  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:55:49.864  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:55:50.299  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:55:50.781  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:56:06.001  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 1/60]
2019-08-08 12:56:08.531  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:56:08.532  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:56:09.110  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:56:09.748  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:56:24.944  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 2/60]
2019-08-08 12:56:27.557  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:56:27.558  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:56:27.851  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:56:28.490  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 2/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:56:43.628  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 3/60]
2019-08-08 12:56:46.417  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:56:46.418  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:56:46.863  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:56:47.647  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 3/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:57:02.711  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 4/60]
2019-08-08 12:57:05.560  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:57:05.561  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:57:05.854  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:57:06.906  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 4/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:57:22.062  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 5/60]
2019-08-08 12:57:24.921  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:57:24.922  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:57:25.381  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:57:26.015  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 5/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:57:41.111  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 6/60]
2019-08-08 12:57:43.638  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:57:43.639  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:57:43.946  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:57:44.679  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 6/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:57:59.830  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 7/60]
2019-08-08 12:58:02.401  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:58:02.402  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:58:02.702  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:58:03.665  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 7/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:58:18.774  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 8/60]
2019-08-08 12:58:21.437  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:58:21.438  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:58:21.943  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:58:22.703  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 8/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:58:38.009  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 9/60]
2019-08-08 12:58:40.656  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:58:40.658  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:58:41.130  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:58:41.776  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 9/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:58:56.833  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 10/60]
2019-08-08 12:59:00.165  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:59:00.166  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:59:00.443  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:59:00.979  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 10/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:59:16.062  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 11/60]
2019-08-08 12:59:18.816  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:59:18.817  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:59:19.221  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:59:20.037  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 11/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:59:35.232  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 12/60]
2019-08-08 12:59:37.940  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:59:37.941  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:59:38.517  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:59:38.985  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 12/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 12:59:54.079  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 13/60]
2019-08-08 12:59:56.617  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 12:59:56.618  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 12:59:56.928  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 12:59:57.430  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 13/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:00:12.517  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 14/60]
2019-08-08 13:00:15.125  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:00:15.127  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:00:15.631  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:00:16.303  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 14/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:00:31.491  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 15/60]
2019-08-08 13:00:34.724  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:00:34.726  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:00:35.026  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:00:35.691  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 15/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:00:50.806  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 16/60]
2019-08-08 13:00:53.315  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:00:53.316  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:00:53.593  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:00:54.135  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 16/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:01:09.232  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 17/60]
2019-08-08 13:01:12.456  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:01:12.457  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:01:12.921  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:01:13.604  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 17/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:01:28.746  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 18/60]
2019-08-08 13:01:32.227  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:01:32.228  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:01:32.977  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:01:33.604  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 18/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:01:48.735  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 19/60]
2019-08-08 13:01:52.048  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:01:52.049  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:01:52.324  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:01:53.180  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 19/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:02:08.342  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 20/60]
2019-08-08 13:02:11.499  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:02:11.500  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:02:11.795  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:02:12.518  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 20/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:02:27.676  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 21/60]
2019-08-08 13:02:30.544  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:02:30.545  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:02:30.990  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:02:31.593  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 21/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:02:46.749  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 22/60]
2019-08-08 13:02:49.792  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:02:49.793  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:02:50.280  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:02:50.767  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 22/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:03:06.113  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 23/60]
2019-08-08 13:03:08.923  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:03:08.925  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:03:09.298  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:03:10.272  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 23/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:03:25.419  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 24/60]
2019-08-08 13:03:27.899  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:03:27.901  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:03:28.455  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:03:29.140  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 24/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:03:44.292  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 25/60]
2019-08-08 13:03:46.916  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:03:46.917  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:03:47.422  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:03:48.140  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 25/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:04:03.291  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 26/60]
2019-08-08 13:04:06.018  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:04:06.020  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:04:06.464  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:04:07.291  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 26/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:04:22.456  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 27/60]
2019-08-08 13:04:25.178  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:04:25.180  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:04:25.625  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:04:26.423  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 27/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:04:41.503  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 28/60]
2019-08-08 13:04:44.523  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:04:44.524  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:04:44.823  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:04:45.513  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 28/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:05:00.589  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 29/60]
2019-08-08 13:05:03.959  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:05:03.960  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:05:04.223  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:05:04.751  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 29/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:05:19.893  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 30/60]
2019-08-08 13:05:22.571  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:05:22.573  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:05:22.845  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:05:23.618  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 30/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:05:38.723  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 31/60]
2019-08-08 13:05:41.413  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:05:41.414  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:05:41.695  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:05:42.342  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 31/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:05:57.496  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 32/60]
2019-08-08 13:06:00.476  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:06:00.478  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:06:00.758  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:06:01.438  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 32/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:06:16.588  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 33/60]
2019-08-08 13:06:19.336  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:06:19.338  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:06:20.127  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:06:20.932  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 33/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:06:36.093  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 34/60]
2019-08-08 13:06:38.891  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:06:38.892  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:06:39.206  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:06:39.876  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 34/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:06:54.994  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 35/60]
2019-08-08 13:06:57.825  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:06:57.826  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:06:58.101  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:06:58.698  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 35/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:07:13.810  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 36/60]
2019-08-08 13:07:16.566  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:07:16.568  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:07:16.863  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:07:17.349  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 36/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:07:32.451  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 37/60]
2019-08-08 13:07:35.561  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:07:35.562  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:07:35.839  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:07:36.426  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 37/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:07:51.578  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 38/60]
2019-08-08 13:07:54.020  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:07:54.022  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:07:54.302  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:07:54.920  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 38/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:08:10.066  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 39/60]
2019-08-08 13:08:12.734  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:08:12.735  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:08:13.012  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:08:13.613  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 39/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:08:28.741  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 40/60]
2019-08-08 13:08:31.387  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:08:31.388  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:08:32.048  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:08:32.908  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 40/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:08:48.039  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 41/60]
2019-08-08 13:08:50.771  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:08:50.772  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:08:51.188  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:08:51.997  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 41/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:09:07.103  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 42/60]
2019-08-08 13:09:10.624  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:09:10.625  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:09:10.910  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:09:11.599  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 42/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:09:26.732  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 43/60]
2019-08-08 13:09:29.923  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:09:29.925  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:09:30.293  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:09:31.094  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 43/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:09:46.163  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 44/60]
2019-08-08 13:09:48.850  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:09:48.851  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:09:49.139  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:09:49.904  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 44/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:10:05.002  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 45/60]
2019-08-08 13:10:07.941  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:10:07.943  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:10:08.473  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:10:09.315  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 45/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

2019-08-08 13:10:24.406  CFY <azure> [resource_group_pflaaj.create] Sending task 'cloudify_azure.resources.resourcegroup.create' [retry 46/60]
2019-08-08 13:10:27.187  LOG <azure> [resource_group_pflaaj.create] INFO: Creating Resource Group "01wordpress"
2019-08-08 13:10:27.188  LOG <azure> [resource_group_pflaaj.create] INFO: request({'url': 'https://management.azure.com/subscriptions/9cf8b4c4-cd80-43a7-bab0-9a6bf01d3b25/resourceGroups/01wordpress', 'verify': True, 'json': {'location': 'East-US', 'tags': None}, 'params': {'api-version': u'2017-05-10'}, 'method': 'put'})
2019-08-08 13:10:27.466  LOG <azure> [resource_group_pflaaj.create] INFO: BAD REQUEST: response: {"error":{"code":"InvalidResourceLocation","message":"The specified location 'East-US' is invalid. A location must consist of characters, whitespace, digit, or following symbols '(,)'."}}
2019-08-08 13:10:28.189  CFY <azure> [resource_group_pflaaj.create] Task failed 'cloudify_azure.resources.resourcegroup.create' -> 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST' [retry 46/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/resourcegroup.py", line 65, in create
    'tags': ctx.node.properties.get('tags')
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/utils.py", line 103, in task_resource_create
    resource.create(name, params)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-azure-plugin-2.1.7/lib/python2.7/site-packages/cloudify_azure/resources/base.py", line 210, in create
    'Recieved HTTP 400 BAD REQUEST', res.json())
UnexpectedResponse: 'Unexpected response recieved. Recieved HTTP 400 BAD REQUEST'

Timed out waiting for workflow 'install' of deployment 'azure' to end. The execution may still be running properly; however, the command-line utility was instructed to wait up to 900 seconds for its completion.

* Run 'cfy executions list' to determine the execution's status.
* Run 'cfy executions cancel 842bd5f5-2051-447a-a825-4845f0d3dcdc' to cancel the running workflow.
* Run 'cfy events list --tail 842bd5f5-2051-447a-a825-4845f0d3dcdc' to retrieve the execution's events/logs
