Executing workflow `uninstall` on deployment `gcp` [timeout=900 seconds]
2019-08-10 22:23:11.375  CFY <gcp> Starting 'uninstall' workflow execution
2019-08-10 22:23:12.634  CFY <gcp> [config-database_ahygw5->vm-database_2ajtp1|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 22:23:13.494  CFY <gcp> [firewall_xpo3tx] Validating node instance after deletion: nothing to do
2019-08-10 22:23:13.662  CFY <gcp> [config-database_ahygw5] Validating node instance after deletion: nothing to do
2019-08-10 22:23:13.816  CFY <gcp> [config-wordpress_n6v8pi->vm-app2_olccmt|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 22:23:13.869  CFY <gcp> [config-wordpress_n6v8pi] Validating node instance after deletion: nothing to do
2019-08-10 22:23:15.003  CFY <gcp> [config-database_ahygw5] Stop: instance already uninitialized
2019-08-10 22:23:15.140  CFY <gcp> [firewall_xpo3tx] Stop: instance already uninitialized
2019-08-10 22:23:15.237  CFY <gcp> [config-wordpress_n6v8pi] Stop: instance already uninitialized
2019-08-10 22:23:16.656  CFY <gcp> [config-database_ahygw5] Delete: instance already uninitialized
2019-08-10 22:23:16.865  CFY <gcp> [firewall_xpo3tx] Delete: instance already uninitialized
2019-08-10 22:23:17.008  CFY <gcp> [config-wordpress_n6v8pi] Delete: instance already uninitialized
2019-08-10 22:23:17.219  CFY <gcp> [config-database_ahygw5->vm-database_2ajtp1|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 22:23:17.755  CFY <gcp> [config-database_ahygw5] Deleted node instance
2019-08-10 22:23:18.478  CFY <gcp> [firewall_xpo3tx] Deleted node instance
2019-08-10 22:23:19.286  CFY <gcp> [config-wordpress_n6v8pi] Deleted node instance
2019-08-10 22:23:19.886  CFY <gcp> [config-wordpress_n6v8pi->vm-app2_olccmt|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 22:23:19.979  CFY <gcp> [config-wordpress_n6v8pi->vm-app1_u2gugw|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 22:23:22.648  CFY <gcp> [config-wordpress_n6v8pi->vm-app1_u2gugw|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-10 22:23:22.956  CFY <gcp> [vm-app1_u2gugw] Validating node instance after deletion: nothing to do
2019-08-10 22:23:23.345  CFY <gcp> [vm-app2_olccmt] Validating node instance after deletion: nothing to do
2019-08-10 22:23:23.427  CFY <gcp> [vm-app2_olccmt] Stop: instance already uninitialized
2019-08-10 22:23:23.487  CFY <gcp> [vm-app1_u2gugw] Stop: instance already uninitialized
2019-08-10 22:23:23.874  CFY <gcp> [vm-app2_olccmt] Delete: instance already uninitialized
2019-08-10 22:23:23.946  CFY <gcp> [vm-app2_olccmt] Deleted node instance
2019-08-10 22:23:24.152  CFY <gcp> [vm-app1_u2gugw] Delete: instance already uninitialized
2019-08-10 22:23:24.505  CFY <gcp> [vm-app1_u2gugw] Deleted node instance
2019-08-10 22:23:24.974  CFY <gcp> [vm-database_2ajtp1] Validating node instance after deletion: nothing to do
2019-08-10 22:23:25.168  CFY <gcp> [vm-database_2ajtp1] Stop: instance already uninitialized
2019-08-10 22:23:25.493  CFY <gcp> [vm-database_2ajtp1] Delete: instance already uninitialized
2019-08-10 22:23:25.574  CFY <gcp> [vm-database_2ajtp1] Deleted node instance
2019-08-10 22:23:26.103  CFY <gcp> [subnet_37dawf] Validating node instance after deletion: nothing to do
2019-08-10 22:23:26.349  CFY <gcp> [subnet_37dawf] Stop: instance already uninitialized
2019-08-10 22:23:26.631  CFY <gcp> [subnet_37dawf] Delete: instance already uninitialized
2019-08-10 22:23:26.951  CFY <gcp> [subnet_37dawf] Deleted node instance
2019-08-10 22:23:27.210  CFY <gcp> [network_x0bbb3] Stopping node instance
2019-08-10 22:23:27.608  CFY <gcp> [network_x0bbb3] Validating node instance after deletion: nothing to do
2019-08-10 22:23:27.802  CFY <gcp> [network_x0bbb3] Stopped node instance: nothing to do
2019-08-10 22:23:28.674  CFY <gcp> [network_x0bbb3] Unlinking relationships
2019-08-10 22:23:29.039  CFY <gcp> [network_x0bbb3] Relationships unlinked
2019-08-10 22:23:29.142  CFY <gcp> [network_x0bbb3] Deleting node instance
2019-08-10 22:23:29.408  CFY <gcp> [network_x0bbb3.delete] Sending task 'cloudify_gcp.compute.network.delete'
2019-08-10 22:23:31.413  LOG <gcp> [network_x0bbb3.delete] INFO: Delete network network-x0bbb3
2019-08-10 22:23:33.022  LOG <gcp> [network_x0bbb3.delete] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/network.py", line 215, in delete
    utils.delete_if_not_external(network)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 175, in delete_if_not_external
    return resource.delete()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/network.py", line 80, in delete
    network=self.name).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/global/networks/network-x0bbb3?alt=json returned "The resource 'projects/node2faas-248113/global/networks/network-x0bbb3' was not found">
 with message <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/global/networks/network-x0bbb3?alt=json returned "The resource 'projects/node2faas-248113/global/networks/network-x0bbb3' was not found">
2019-08-10 22:23:33.023  LOG <gcp> [network_x0bbb3.delete] ERROR: Error Message 
2019-08-10 22:23:33.540  CFY <gcp> [network_x0bbb3.delete] Task failed 'cloudify_gcp.compute.network.delete'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError

2019-08-10 22:23:33.563  CFY <gcp> [network_x0bbb3] Deleted node instance
2019-08-10 22:23:34.115  CFY <gcp> 'uninstall' workflow execution succeeded
Finished executing workflow uninstall on deployment gcp
* Run 'cfy events list dfaebda4-0672-451a-a5db-f103e9033738' to retrieve the execution's events/logs
Trying to delete deployment gcp...
Deployment deleted
Deleting blueprint cloudify-wordpress-blueprint-gcp...
Blueprint deleted
