Executing workflow `uninstall` on deployment `gcp` [timeout=900 seconds]
2019-08-11 00:47:48.080  CFY <gcp> Starting 'uninstall' workflow execution
2019-08-11 00:47:49.080  CFY <gcp> [config-wordpress_0xb73n->vm-app2_w0j2od|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 00:47:50.016  CFY <gcp> [config-database_q4p2r2->vm-database_gxkijq|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 00:47:51.088  CFY <gcp> [config-wordpress_0xb73n] Validating node instance after deletion: nothing to do
2019-08-11 00:47:51.385  CFY <gcp> [firewall_t6f01k] Stopping node instance
2019-08-11 00:47:51.907  CFY <gcp> [config-database_q4p2r2] Validating node instance after deletion: nothing to do
2019-08-11 00:47:52.055  CFY <gcp> [config-wordpress_0xb73n] Stop: instance already uninitialized
2019-08-11 00:47:52.203  CFY <gcp> [firewall_t6f01k] Validating node instance after deletion: nothing to do
2019-08-11 00:47:52.329  CFY <gcp> [config-database_q4p2r2] Stop: instance already uninitialized
2019-08-11 00:47:52.766  CFY <gcp> [firewall_t6f01k] Stopped node instance: nothing to do
2019-08-11 00:47:52.919  CFY <gcp> [config-wordpress_0xb73n->vm-app2_w0j2od|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 00:47:53.172  CFY <gcp> [config-wordpress_0xb73n->vm-app1_asb9gv|unlink] Sending task 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 00:47:53.332  CFY <gcp> [config-wordpress_0xb73n] Delete: instance already uninitialized
2019-08-11 00:47:54.224  CFY <gcp> [config-database_q4p2r2] Delete: instance already uninitialized
2019-08-11 00:47:54.855  CFY <gcp> [firewall_t6f01k] Unlinking relationships
2019-08-11 00:47:54.890  CFY <gcp> [config-database_q4p2r2->vm-database_gxkijq|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 00:47:55.096  CFY <gcp> [config-wordpress_0xb73n] Deleted node instance
2019-08-11 00:47:55.652  CFY <gcp> [config-database_q4p2r2] Deleted node instance
2019-08-11 00:47:55.772  CFY <gcp> [firewall_t6f01k] Relationships unlinked
2019-08-11 00:47:56.289  CFY <gcp> [firewall_t6f01k] Deleting node instance
2019-08-11 00:47:56.652  CFY <gcp> [firewall_t6f01k.delete] Sending task 'cloudify_gcp.compute.firewall.delete'
2019-08-11 00:47:57.326  CFY <gcp> [config-wordpress_0xb73n->vm-app1_asb9gv|unlink] Task succeeded 'cloudify_ansible.tasks.ansible_remove_host'
2019-08-11 00:47:57.964  CFY <gcp> [vm-app1_asb9gv] Validating node instance after deletion: nothing to do
2019-08-11 00:47:58.383  CFY <gcp> [vm-app2_w0j2od] Validating node instance after deletion: nothing to do
2019-08-11 00:47:58.483  CFY <gcp> [vm-app1_asb9gv] Stop: instance already uninitialized
2019-08-11 00:47:58.585  CFY <gcp> [vm-app2_w0j2od] Stop: instance already uninitialized
2019-08-11 00:47:59.328  CFY <gcp> [vm-app1_asb9gv] Delete: instance already uninitialized
2019-08-11 00:47:59.423  CFY <gcp> [vm-app1_asb9gv] Deleted node instance
2019-08-11 00:47:59.679  CFY <gcp> [vm-app2_w0j2od] Delete: instance already uninitialized
2019-08-11 00:47:59.871  CFY <gcp> [vm-app2_w0j2od] Deleted node instance
2019-08-11 00:48:00.240  LOG <gcp> [firewall_t6f01k.delete] INFO: Delete firewall rule firewall-t6f01k from network https://www.googleapis.com/compute/v1/projects/node2faas-248113/global/networks/network-7hncki
2019-08-11 00:48:01.090  CFY <gcp> [vm-database_gxkijq] Stopping node instance
2019-08-11 00:48:01.156  CFY <gcp> [vm-database_gxkijq] Validating node instance after deletion: nothing to do
2019-08-11 00:48:01.482  CFY <gcp> [vm-database_gxkijq] Stopped node instance: nothing to do
2019-08-11 00:48:01.915  CFY <gcp> [vm-database_gxkijq] Unlinking relationships
2019-08-11 00:48:02.237  CFY <gcp> [vm-database_gxkijq] Relationships unlinked
2019-08-11 00:48:02.499  CFY <gcp> [vm-database_gxkijq] Deleting node instance
2019-08-11 00:48:02.705  CFY <gcp> [vm-database_gxkijq.delete] Sending task 'cloudify_gcp.compute.instance.delete'
2019-08-11 00:48:02.916  CFY <gcp> [firewall_t6f01k.delete] Task succeeded 'cloudify_gcp.compute.firewall.delete'
2019-08-11 00:48:03.656  CFY <gcp> [firewall_t6f01k] Deleted node instance
2019-08-11 00:48:05.502  LOG <gcp> [vm-database_gxkijq.delete] INFO: Delete instance wordpressdatabase
2019-08-11 00:48:07.096  LOG <gcp> [vm-database_gxkijq.delete] ERROR: Error traceback Traceback (most recent call last):
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 262, in _decorator
    return func(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 457, in delete
    utils.delete_if_not_external(instance)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 175, in delete_if_not_external
    return resource.delete()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 233, in wrapper
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/gcp.py", line 34, in _decorator
    response = func(self, *args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/compute/instance.py", line 133, in delete
    instance=self.name).execute()
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/googleapiclient/http.py", line 832, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase' was not found">
 with message <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase?alt=json returned "The resource 'projects/node2faas-248113/zones/southamerica-east1-c/instances/wordpressdatabase' was not found">
2019-08-11 00:48:07.096  LOG <gcp> [vm-database_gxkijq.delete] ERROR: Error Message 
2019-08-11 00:48:07.669  CFY <gcp> [vm-database_gxkijq.delete] Task failed 'cloudify_gcp.compute.instance.delete'
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 461, in handle
    result = self._run_operation_func(ctx, kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _run_operation_func
    return self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/cloudify-gcp-plugin-1.4.4/lib/python2.7/site-packages/cloudify_gcp/utils.py", line 277, in _decorator
    raise NonRecoverableError(error.message)
NonRecoverableError

2019-08-11 00:48:07.964  CFY <gcp> [vm-database_gxkijq] Deleted node instance
2019-08-11 00:48:08.286  CFY <gcp> [subnet_ivm4jc] Stopping node instance
2019-08-11 00:48:08.633  CFY <gcp> [subnet_ivm4jc] Validating node instance after deletion: nothing to do
2019-08-11 00:48:08.686  CFY <gcp> [subnet_ivm4jc] Stopped node instance: nothing to do
2019-08-11 00:48:09.006  CFY <gcp> [subnet_ivm4jc] Unlinking relationships
2019-08-11 00:48:09.273  CFY <gcp> [subnet_ivm4jc] Relationships unlinked
2019-08-11 00:48:09.488  CFY <gcp> [subnet_ivm4jc] Deleting node instance
2019-08-11 00:48:09.626  CFY <gcp> [subnet_ivm4jc.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete'
2019-08-11 00:48:11.570  LOG <gcp> [subnet_ivm4jc.delete] INFO: Delete subnetwork subnet-ivm4jc
2019-08-11 00:48:13.952  CFY <gcp> [subnet_ivm4jc.delete] Task rescheduled 'cloudify_gcp.compute.subnetwork.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-11 00:48:29.049  CFY <gcp> [subnet_ivm4jc.delete] Sending task 'cloudify_gcp.compute.subnetwork.delete' [retry 1/60]
2019-08-11 00:48:32.886  CFY <gcp> [subnet_ivm4jc.delete] Task succeeded 'cloudify_gcp.compute.subnetwork.delete' [retry 1/60]
2019-08-11 00:48:33.176  CFY <gcp> [subnet_ivm4jc] Deleted node instance
2019-08-11 00:48:33.424  CFY <gcp> [network_7hncki] Stopping node instance
2019-08-11 00:48:33.811  CFY <gcp> [network_7hncki] Validating node instance after deletion: nothing to do
2019-08-11 00:48:33.915  CFY <gcp> [network_7hncki] Stopped node instance: nothing to do
2019-08-11 00:48:34.238  CFY <gcp> [network_7hncki] Unlinking relationships
2019-08-11 00:48:34.504  CFY <gcp> [network_7hncki] Relationships unlinked
2019-08-11 00:48:34.733  CFY <gcp> [network_7hncki] Deleting node instance
2019-08-11 00:48:34.928  CFY <gcp> [network_7hncki.delete] Sending task 'cloudify_gcp.compute.network.delete'
2019-08-11 00:48:37.117  LOG <gcp> [network_7hncki.delete] INFO: Delete network network-7hncki
2019-08-11 00:48:39.651  CFY <gcp> [network_7hncki.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation started
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation started

2019-08-11 00:48:54.774  CFY <gcp> [network_7hncki.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 1/60]
2019-08-11 00:48:58.883  CFY <gcp> [network_7hncki.delete] Task rescheduled 'cloudify_gcp.compute.network.delete' -> Operation not completed yet: RUNNING [retry_after=30] [retry 1/60]
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 813, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 464, in handle
    raise ctx.operation._operation_retry
OperationRetry: Operation not completed yet: RUNNING [retry_after=30]

2019-08-11 00:49:29.065  CFY <gcp> [network_7hncki.delete] Sending task 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-11 00:49:32.727  CFY <gcp> [network_7hncki.delete] Task succeeded 'cloudify_gcp.compute.network.delete' [retry 2/60]
2019-08-11 00:49:32.929  CFY <gcp> [network_7hncki] Deleted node instance
2019-08-11 00:49:33.375  CFY <gcp> 'uninstall' workflow execution succeeded
Finished executing workflow uninstall on deployment gcp
* Run 'cfy events list 8cf83502-746d-4b95-8350-15080b6075c6' to retrieve the execution's events/logs
Trying to delete deployment gcp...
Deployment deleted
Deleting blueprint cloudify-wordpress-blueprint-gcp...
Blueprint deleted
